import test from "node:test";
import assert from "node:assert/strict";
import {randomUUID} from "node:crypto";
import {SQLiteLocalStore} from "../src/offline/store.mjs";
import {OfflinePOSEngine} from "../src/offline/engine.mjs";
import {SyncProtocol,ReconciliationEngine} from "../src/sync/protocol.mjs";
import {CanonicalSyncServer} from "../src/sync/server.mjs";
import {compareReconciliation} from "../src/sync/reconciliation.mjs";
function fixture(){const store=new SQLiteLocalStore(),ids={tenantId:randomUUID(),outletId:randomUUID(),deviceId:randomUUID(),actorId:randomUUID(),shiftId:randomUUID(),variantId:randomUUID()};store.createDevice(ids);const engine=new OfflinePOSEngine(store,ids.deviceId);engine.openShift({shiftId:ids.shiftId});return{store,engine,ids};}
const sale=(ids,orderId=randomUUID(),amount=10000)=>({orderId,items:[{productVariantId:ids.variantId,quantity:1,unitPriceMinor:amount,lineTotalMinor:amount}],subtotalMinor:amount,totalMinor:amount,paymentMinor:amount});
test("sequence is assigned and ACK advances cursor",async()=>{const{store,engine}=fixture();engine.sell(sale(fixture().ids));store.close();});
test("sync ACK records server cursor",async()=>{const{store,engine,ids}=fixture();engine.sell(sale(ids));const server=new CanonicalSyncServer(),r=await new SyncProtocol(store,server).drain();assert.equal(r[0].status,"ACKED");assert.equal(r[0].serverCursor,1);const row=store.outboxStatus(r[0].eventId);assert.equal(row.server_cursor,1);assert.equal(row.server_sequence,1);store.close();});
test("timeout after server acceptance is safe on retry",async()=>{const{store,engine,ids}=fixture(),server=new CanonicalSyncServer(),orderId=randomUUID();engine.sell(sale(ids,orderId));let first=true;const wrapped={accept:async e=>{const r=server.accept(e);if(first){first=false;throw new Error("ACK_TIMEOUT");}return r;}};const sync=new SyncProtocol(store,wrapped);const a=await sync.drain();assert.equal(a[0].status,"RETRY");store.exec("UPDATE outbox SET next_attempt_at=NULL WHERE event_id=?",[a[0].eventId]);const b=await sync.drain();assert.equal(b[0].status,"ACKED");assert.equal(server.events.size,1);assert.equal(server.sequence,1);store.close();});
test("idempotency key reuse with different payload is explicit conflict",()=>{const s=new CanonicalSyncServer(),base={eventId:randomUUID(),tenantId:randomUUID(),aggregateId:randomUUID(),idempotencyKey:"k",payload:{totalMinor:1000}};assert.equal(s.accept(base).status,"ACK");assert.equal(s.accept({...base,eventId:randomUUID(),payload:{totalMinor:2000}}).code,"IDEMPOTENCY_KEY_REUSE");});
test("reconciliation passes after sync",async()=>{const{store,engine,ids}=fixture();engine.sell(sale(ids));engine.sell(sale(ids));const server=new CanonicalSyncServer();await new SyncProtocol(store,server).drain();const r=new ReconciliationEngine(store,server).run({tenantId:ids.tenantId,deviceId:ids.deviceId,periodStart:"2026-10-07",periodEnd:"2026-10-07"});assert.equal(r.status,"PASS");assert.deepEqual(r.reasons,[]);store.close();});
test("reconciliation never silently repairs mismatch",()=>{const r=compareReconciliation({transactionCount:2,totalMinor:20000,paymentTotalMinor:20000,outstandingSyncCount:0},{transactionCount:1,totalMinor:10000,paymentTotalMinor:10000,outstandingSyncCount:0});assert.equal(r.status,"RECONCILIATION_REQUIRED");assert.deepEqual(r.mismatches,["transactionCount","totalMinor","paymentTotalMinor"]);});
test("telemetry records ACK and retry outcomes",async()=>{const{store,engine,ids}=fixture();engine.sell(sale(ids));const server=new CanonicalSyncServer();await new SyncProtocol(store,server).drain();const row=store.all("SELECT * FROM sync_telemetry").at(0);assert.equal(row.outcome,"ACK");assert.equal(row.attempt,1);store.close();});
