import fs from "node:fs"; import path from "node:path";
const root=path.resolve("db/migrations");
const files=fs.readdirSync(root).filter(f=>f.endsWith(".sql")).sort();
if(files.length<5)throw new Error("Expected at least 5 canonical migrations");
const required=["tenant_id","idempotency_key","correlation_id","audit_log","sales_ledger","inventory_ledger","payment","order_item","cost_layer","inventory_projection","cash_closing","payment_reconciliation","variance_case","post_inventory_sale","value_minor","pilot_run","pilot_outlet","pilot_metric","support_incident","uptime_heartbeat","pilot_gate","feature_flag","release_record","operational_event","role_permission","user_outlet_scope","has_permission","has_outlet_access","assert_trusted_device"];
const sql=files.map(f=>fs.readFileSync(path.join(root,f),"utf8")).join("\n").toLowerCase();
for(const token of required)if(!sql.includes(token))throw new Error("Missing schema contract: "+token);
if(!sql.includes("enable row level security"))throw new Error("RLS is required");
if(!/unique\s*\(\s*tenant_id\s*,\s*idempotency_key\s*\)/.test(sql))throw new Error("Idempotency uniqueness contract is missing");
if(!sql.includes("force row level security"))throw new Error("Forced RLS contract is missing");
if(!sql.includes("prevent_ledger_mutation"))throw new Error("Ledger immutability trigger is missing");
console.log("SCHEMA STATIC CONTRACT: PASS");
console.log("Migrations:",files.join(", "));
